apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: epc2jleor-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/epc2jleor-dotnet-basic-gitops